#!/usr/bin/env bash
#
# generate-videos.sh — Produces MP4 demo videos with voice narration
# from the assets generated by RecordingDemoTest.
#
# Prerequisites:
#   - rsvg-convert  (brew install librsvg)
#   - ffmpeg        (brew install ffmpeg)
#   - edge-tts      (pipx install edge-tts) — neural TTS, preferred
#   - macOS say     (built-in fallback)
#   - python3       (for JSON parsing)
#
# Usage:
#   1. Generate recording assets:
#        mvn test -B -Dtest=RecordingDemoTest -Dpilot.recordings=true
#   2. Produce videos:
#        ./generate-videos.sh
#   3. Or produce a single video:
#        ./generate-videos.sh pom-viewer
#
# Environment variables:
#   PILOT_TTS_ENGINE  — "edge-tts" (default) or "say" (macOS fallback)
#   PILOT_TTS_VOICE   — Voice name (default: en-US-AndrewNeural for edge-tts,
#                        Samantha for say)
#   PILOT_VIDEO_DPI   — SVG render DPI (default: 144, use 288 for 4K)
#
set -euo pipefail

RECORDINGS_DIR="docs/recordings"
OUTPUT_DIR="docs/videos"
DPI="${PILOT_VIDEO_DPI:-144}"

# ── TTS engine selection ────────────────────────────────────────────

TTS_ENGINE="${PILOT_TTS_ENGINE:-auto}"
if [[ "$TTS_ENGINE" == "auto" ]]; then
    if command -v edge-tts >/dev/null 2>&1; then
        TTS_ENGINE="edge-tts"
    elif command -v say >/dev/null 2>&1; then
        TTS_ENGINE="say"
    else
        echo "ERROR: No TTS engine found. Install edge-tts: pipx install edge-tts" >&2
        exit 1
    fi
fi

case "$TTS_ENGINE" in
    edge-tts)
        TTS_VOICE="${PILOT_TTS_VOICE:-en-US-AndrewNeural}"
        echo "TTS engine: edge-tts (voice: $TTS_VOICE)"
        ;;
    say)
        TTS_VOICE="${PILOT_TTS_VOICE:-Samantha}"
        echo "TTS engine: macOS say (voice: $TTS_VOICE)"
        ;;
    *)
        echo "ERROR: Unknown TTS engine: $TTS_ENGINE" >&2
        exit 1
        ;;
esac

# ── Preflight checks ────────────────────────────────────────────────

check_prerequisites() {
    local missing=()
    command -v rsvg-convert >/dev/null || missing+=(rsvg-convert)
    command -v ffmpeg       >/dev/null || missing+=(ffmpeg)
    command -v ffprobe      >/dev/null || missing+=(ffprobe)
    command -v python3      >/dev/null || missing+=(python3)

    if [[ ${#missing[@]} -gt 0 ]]; then
        echo "ERROR: Missing required tools: ${missing[*]}" >&2
        echo "Install with: brew install librsvg ffmpeg" >&2
        exit 1
    fi
}

# ── JSON helpers (python3 one-liners) ────────────────────────────────

json_scene_count() {
    python3 -c "import json,sys; print(len(json.load(open(sys.argv[1]))['scenes']))" "$1"
}

json_scene_text() {
    python3 -c "import json,sys; print(json.load(open(sys.argv[1]))['scenes'][int(sys.argv[2])]['text'])" "$1" "$2"
}

json_title() {
    python3 -c "import json,sys; print(json.load(open(sys.argv[1]))['title'])" "$1"
}

# ── Per-video pipeline ───────────────────────────────────────────────

generate_video() {
    local name=$1
    local narration_file="$RECORDINGS_DIR/${name}.narration.json"
    local frames_dir="$RECORDINGS_DIR/$name"

    if [[ ! -f "$narration_file" ]]; then
        echo "SKIP: $narration_file not found" >&2
        return 1
    fi

    local work_dir
    work_dir=$(mktemp -d)
    trap "rm -rf '$work_dir'" RETURN

    local title
    title=$(json_title "$narration_file")
    local num_scenes
    num_scenes=$(json_scene_count "$narration_file")

    echo "=== $title ($num_scenes scenes) ==="

    # ── Step 1: SVG → PNG ────────────────────────────────────────────
    echo "  [1/5] Rendering SVG frames to PNG..."
    for svg in "$frames_dir"/frame-*.svg; do
        local base
        base=$(basename "$svg" .svg)
        # Patch SVG for rsvg-convert:
        #  - xml:space="preserve" keeps leading &#160; whitespace
        #  - Remap CGA ANSI palette to Ghostty default theme
        local patched="$work_dir/${base}.svg"
        sed -e 's/<svg /<svg xml:space="preserve" /' \
            -e 's/#0000aa/#88a1bb/g' \
            -e 's/#00aa00/#b7bd73/g' \
            -e 's/#00aaaa/#95bdb7/g' \
            -e 's/#aa5500/#e9c880/g' \
            -e 's/#aa0000/#cc6666/g' \
            -e 's/#aa00aa/#b294bb/g' \
            -e 's/#555555/#969896/g' \
            -e 's/#292929/#1d1f21/g' \
            "$svg" > "$patched"
        rsvg-convert -d "$DPI" -p "$DPI" "$patched" -o "$work_dir/${base}.png"
    done

    # ── Step 2: Generate TTS audio per scene ─────────────────────────
    echo "  [2/5] Generating voice narration ($TTS_ENGINE)..."
    local -a durations=()
    for i in $(seq 0 $((num_scenes - 1))); do
        local idx
        idx=$(printf '%02d' "$i")
        local text
        text=$(json_scene_text "$narration_file" "$i")
        local m4a="$work_dir/narration-${idx}.m4a"

        case "$TTS_ENGINE" in
            edge-tts)
                local mp3="$work_dir/narration-${idx}.mp3"
                edge-tts --voice "$TTS_VOICE" --text "$text" \
                    --write-media "$mp3" 2>/dev/null
                ffmpeg -y -i "$mp3" -c:a aac -b:a 128k "$m4a" -loglevel error
                ;;
            say)
                local aiff="$work_dir/narration-${idx}.aiff"
                say -v "$TTS_VOICE" -o "$aiff" "$text"
                ffmpeg -y -i "$aiff" -c:a aac -b:a 128k "$m4a" -loglevel error
                ;;
        esac

        # Measure duration
        local dur
        dur=$(ffprobe -v error -show_entries format=duration \
            -of default=noprint_wrappers=1:nokey=1 "$m4a")
        durations+=("$dur")
    done

    # ── Step 3: Build video from PNG frames ──────────────────────────
    echo "  [3/5] Assembling video frames..."
    local concat_file="$work_dir/concat.txt"
    local total_video_duration=0

    for i in $(seq 0 $((num_scenes - 1))); do
        local idx
        idx=$(printf '%02d' "$i")
        # Frame duration = audio duration + padding (min 2.5s)
        local frame_dur
        frame_dur=$(python3 -c "print(max(2.5, ${durations[$i]} + 0.8))")
        echo "file '${work_dir}/frame-${idx}.png'" >> "$concat_file"
        echo "duration ${frame_dur}" >> "$concat_file"
        total_video_duration=$(python3 -c "print(${total_video_duration} + ${frame_dur})")
    done
    # Repeat last frame (ffmpeg concat demuxer requires it)
    local last_idx
    last_idx=$(printf '%02d' $((num_scenes - 1)))
    echo "file '${work_dir}/frame-${last_idx}.png'" >> "$concat_file"

    ffmpeg -y -f concat -safe 0 -i "$concat_file" \
        -vf "scale=1920:-2:flags=lanczos,format=yuv420p" \
        -c:v libx264 -preset medium -crf 18 \
        -r 30 \
        "$work_dir/video.mp4" -loglevel error

    # ── Step 4: Concatenate audio with timed gaps ────────────────────
    echo "  [4/5] Mixing audio track..."
    # Build a complex filter that pads each audio segment to match frame duration,
    # then concatenates them all.
    local filter_inputs=""
    local filter_graph=""
    local concat_inputs=""

    for i in $(seq 0 $((num_scenes - 1))); do
        local idx
        idx=$(printf '%02d' "$i")
        filter_inputs="$filter_inputs -i $work_dir/narration-${idx}.m4a"

        local frame_dur
        frame_dur=$(python3 -c "print(max(2.5, ${durations[$i]} + 0.8))")
        local silence
        silence=$(python3 -c "print(max(0, ${frame_dur} - ${durations[$i]}))")

        # Pad each audio to exactly the frame duration
        filter_graph="${filter_graph}[${i}:a]apad=pad_dur=${silence},atrim=0:${frame_dur}[a${i}];"
        concat_inputs="${concat_inputs}[a${i}]"
    done

    filter_graph="${filter_graph}${concat_inputs}concat=n=${num_scenes}:v=0:a=1[aout]"

    ffmpeg -y $filter_inputs \
        -filter_complex "$filter_graph" \
        -map '[aout]' -c:a aac -b:a 128k \
        "$work_dir/audio.m4a" -loglevel error

    # ── Step 5: Merge video + audio ──────────────────────────────────
    echo "  [5/5] Producing final MP4..."
    mkdir -p "$OUTPUT_DIR"
    ffmpeg -y -i "$work_dir/video.mp4" -i "$work_dir/audio.m4a" \
        -c:v copy -c:a copy -shortest \
        "$OUTPUT_DIR/${name}.mp4" -loglevel error

    local file_size
    file_size=$(du -h "$OUTPUT_DIR/${name}.mp4" | cut -f1)
    echo "  -> $OUTPUT_DIR/${name}.mp4 (${file_size}, ${total_video_duration}s)"
}

# ── Main ─────────────────────────────────────────────────────────────

main() {
    check_prerequisites

    if [[ $# -gt 0 ]]; then
        # Generate specific video(s)
        for name in "$@"; do
            generate_video "$name"
        done
    else
        # Generate all videos from available narration files
        local count=0
        for narration in "$RECORDINGS_DIR"/*.narration.json; do
            [[ -f "$narration" ]] || continue
            local name
            name=$(basename "$narration" .narration.json)
            generate_video "$name" && ((count++)) || true
        done
        echo ""
        echo "Done! Generated $count videos in $OUTPUT_DIR/"
    fi
}

main "$@"
